### ISSUE TITLE
Your adapter vs. GG Big Data Adapter

### ISSUE THREAD

**Issue by bdolbeare** [MonsantoCo/goldengate-kafka-adapter#1]
Hi,
I stumbled across your project today and think that it looks very interesting.  I was wondering if you have looked at the new Golden Gate Big Data Adapters (there is a Kafka Adapter) for Golden Gate 12.2.1 (GA was late December) and if you have any thoughts on how your adapter compares to the Oracle Kafka Adapter.  I am currently evaluating the Oracle Kafka Adapter which seems to be working; however, it is a bit expensive for a simple adapter (adapter is an additional purchase even though we own Golden Gate) so I was interested in seeing what was involved in writing my own.  As luck would have it, I found your project before I started and it seems to do almost everything I would want.  Can you share any of your experiences with your adapter?  How does it scale?  Have you encountered any problems?  Does the adapter handle DDL changes (e.g. if you add a column to a table will the adapter ABEND or just tack on the new fields to your JSON doc)?
Thanks for sharing your code!

-Brian

**Comment by sumitkulkarni** [comment]
Hi,
I want to read the redo logs from oracle. I have searched a lot for any java solution on this. But finally I got to know that we can read it via Golden-gate or by using log-miner only. Then I found your solution that passing the logs from Golden-gate into the Kafka queue.
But I am worried about how this adapter is working? Will you please tell me about this adapter in brief.

**Comment by rmoff** [comment]
@sumitkulkarni (and others) - from what I've seen, if you are looking to do OGG -> Kafka, you would either use the [native support in OGG for Kafka](http://docs.oracle.com/goldengate/bd1221/gg-bd/GADBD/GUID-2561CA12-9BAC-454B-A2E3-2D36C5C60EE5.htm#GADBD449), or the [Kafka Connect connector for OGG](https://java.net/projects/oracledi/downloads/directory/GoldenGate/Oracle%20GoldenGate%20Adapter%20for%20Kafka%20Connect), produced by Oracle but released open source (example of using it: https://www.confluent.io/blog/streaming-data-oracle-using-oracle-goldengate-kafka-connect/)

**Comment by jasonclark1985** [comment]
At this point, I would agree with @rmoff that there are much better (and supported) options out there.  This adapter was built around 2 years ago before there was native kafka integration with OGG.  I would consider this adapter deprecated.  It has helped us keep the lights on as we transition to a cloud based architecture, but much better options exist now for OGG interaction with Kafka.
